# For making a post request to login a user
POST http://localhost:5000/api/v1/login
content-type: application/json

{
    "email": "dumebi@gmail.com",
    "password": "admin12345"
}

###

# For making request to get all the user's on the database
GET http://localhost:5000/api/v1/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByaXllb2JpQGdtYWlsLmNvbSIsImFjdGl2ZSI6ZmFsc2UsInVzZXJJZCI6IjYwOTAwNjEwZGUyNzljYWQ5YzRhZTc3NyIsImZpcnN0TmFtZSI6IlByaXllIiwibGFzdE5hbWUiOiJPYmFyZW1pIiwiaWF0IjoxNjIwMDUyNDIxLCJleHAiOjE2MjAxMzg4MjF9.ySMGcLJRDj1KId7SL9onqNBWNKSYuvVTRuB3YqgZ9-Q

###

#For getting user by id
GET http://localhost:5000/api/v1/user/60900610de279cad9c4ae777
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByaXllb2JpQGdtYWlsLmNvbSIsImFjdGl2ZSI6ZmFsc2UsInVzZXJJZCI6IjYwOTAwNjEwZGUyNzljYWQ5YzRhZTc3NyIsImZpcnN0TmFtZSI6IlByaXllIiwibGFzdE5hbWUiOiJPYmFyZW1pIiwiaWF0IjoxNjIwMDUyNDIxLCJleHAiOjE2MjAxMzg4MjF9.ySMGcLJRDj1KId7SL9onqNBWNKSYuvVTRuB3YqgZ9-Q

###

# For registering a user into the database
POST http://localhost:5000/api/v1/register
Content-Type: application/json

{
  "firstName": "Dobo",
  "lastName": "Okaja",
  "email": "dumebi@gmail.com",
  "password": "admin12345"
}

###

#For deleting a user
DELETE http://localhost:5000/api/v1/user/delete/60900e41d46aa9b5d85a89b8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByaXllb2JpQGdtYWlsLmNvbSIsImFjdGl2ZSI6ZmFsc2UsInVzZXJJZCI6IjYwOTAwNjEwZGUyNzljYWQ5YzRhZTc3NyIsImZpcnN0TmFtZSI6IlByaXllIiwibGFzdE5hbWUiOiJPYmFyZW1pIiwiaWF0IjoxNjIwMDUyNDIxLCJleHAiOjE2MjAxMzg4MjF9.ySMGcLJRDj1KId7SL9onqNBWNKSYuvVTRuB3YqgZ9-Q

###

# For adding a Category 
POST http://localhost:5000/api/v1/category/addCategory
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1bWViaUBnbWFpbC5jb20iLCJhY3RpdmUiOmZhbHNlLCJ1c2VySWQiOiI2MTNmNTczMTA4MmUyMTNiMDU2YzZkNWEiLCJmaXJzdE5hbWUiOiJEb2JvIiwibGFzdE5hbWUiOiJPa2FqYSIsImlhdCI6MTYzMjI4MTg0MiwiZXhwIjoxNjMyMzY4MjQyfQ.bEQKFNxktom8jwI2hxnifyxf7O7H8yIPv9Q9q2987Kw

{
    "name": "Test Category"
}


###

# For adding a Category 
GET http://localhost:5000/api/v1/categories
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1bWViaUBnbWFpbC5jb20iLCJhY3RpdmUiOmZhbHNlLCJ1c2VySWQiOiI2MTNmNTczMTA4MmUyMTNiMDU2YzZkNWEiLCJmaXJzdE5hbWUiOiJEb2JvIiwibGFzdE5hbWUiOiJPa2FqYSIsImlhdCI6MTYzMjE2ODYxMiwiZXhwIjoxNjMyMjU1MDEyfQ.PjUiC5z8v7TuJSSfnc2DAF8aS9sMdy6USGoUPyqBnPw

###

# For adding a Post 
POST http://localhost:5000/api/v1/post/addpost
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByaXllb2JpQGdtYWlsLmNvbSIsImFjdGl2ZSI6ZmFsc2UsInVzZXJJZCI6IjYwOTAwNjEwZGUyNzljYWQ5YzRhZTc3NyIsImZpcnN0TmFtZSI6IlByaXllIiwibGFzdE5hbWUiOiJPYmFyZW1pIiwiaWF0IjoxNjIwMDUyNDIxLCJleHAiOjE2MjAxMzg4MjF9.ySMGcLJRDj1KId7SL9onqNBWNKSYuvVTRuB3YqgZ9-Q

{
    "name": "Cisco",
    "text": "Havertz after difficult debut campaigns for German stars",
    "category": "60902b3c8d695cced90349ac",
    "draft": true,
    "owner": "60900610de279cad9c4ae777"   
}

###

# For listening all post
GET http://localhost:5000/api/v1/posts
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1bWViaUBnbWFpbC5jb20iLCJhY3RpdmUiOmZhbHNlLCJ1c2VySWQiOiI2MTNmNTczMTA4MmUyMTNiMDU2YzZkNWEiLCJmaXJzdE5hbWUiOiJEb2JvIiwibGFzdE5hbWUiOiJPa2FqYSIsImlhdCI6MTYzMjgwMzI3NCwiZXhwIjoxNjMyODg5Njc0fQ.KxjyoQ42GvyveUjExALFlRgT6lzE6t44ue1UYohH2T8

####

GET http://localhost:5000/api/v1/post/61529948e98a4d26f2a58974
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1bWViaUBnbWFpbC5jb20iLCJhY3RpdmUiOmZhbHNlLCJ1c2VySWQiOiI2MTNmNTczMTA4MmUyMTNiMDU2YzZkNWEiLCJmaXJzdE5hbWUiOiJEb2JvIiwibGFzdE5hbWUiOiJPa2FqYSIsImlhdCI6MTYzMjgwMzI3NCwiZXhwIjoxNjMyODg5Njc0fQ.KxjyoQ42GvyveUjExALFlRgT6lzE6t44ue1UYohH2T8

####

DELETE http://localhost:5000/api/v1/post/delete/60906bb548a546215de8a314
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByaXllb2JpQGdtYWlsLmNvbSIsImFjdGl2ZSI6ZmFsc2UsInVzZXJJZCI6IjYwOTAwNjEwZGUyNzljYWQ5YzRhZTc3NyIsImZpcnN0TmFtZSI6IlByaXllIiwibGFzdE5hbWUiOiJPYmFyZW1pIiwiaWF0IjoxNjIwMDUyNDIxLCJleHAiOjE2MjAxMzg4MjF9.ySMGcLJRDj1KId7SL9onqNBWNKSYuvVTRuB3YqgZ9-Q
