# For making a post request to login a user
POST http://localhost:5000/api/users/login
content-type: application/json

{
    "email": "priyeobi@gmail.com",
    "password": "admin12345"
}

###

# For making request to get all the user's on the database
GET http://localhost:5000/api/users/
Content-Type: application/json

###

#For getting user by id
GET http://localhost:5000/api/users/5ff47dc8f4e29d970f27f54b
Content-Type: application/json

###

# For registering a user into the database
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "firstName": "Priye",
  "lastName": "Obaremi",
  "email": "priyeobi@gmail.com",
  "password": "admin12345",
  "password2": "admin12345"
}

###

#For deleting a user
DELETE http://localhost:5000/api/users/5faa703494ecb24484934df3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOWU3ZDhiMzE1YmI5MGY4NDI4OTNhZSIsImVtYWlsIjoicGFzdG9yQGdtYWlsLmNvbSIsImlhdCI6MTYwNTAwNjEwMCwiZXhwIjoxNjA1MDI3NzAwfQ.4PKxUP_Yzhb8fdiGPTcsPvuqOaaUyoWae8JWKlqs-4E

###

# For adding a Category 
POST http://localhost:5000/api/posts/category
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMDk2YWM0NTBiZGJmMWJhMzA5YzFlZiIsImZpcnN0TmFtZSI6IkN5bnRoaWEiLCJsYXN0TmFtZSI6Ik9rZWtlIiwiZW1haWwiOiJva2VrZUBnbWFpbC5jb20iLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTYxMTI2NDY4MSwiZXhwIjoxNjExMjg2MjgxfQ.IWVpMxcC71JonowksthoVE3xMyzduQqqCH3MCMYRZxU

{
    "name": "Learning Phase"
}


###

# For adding a Category 
GET http://localhost:5000/api/posts/category
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjQ3ZGM4ZjRlMjlkOTcwZjI3ZjU0YiIsImZpcnN0TmFtZSI6IlByaXllIiwibGFzdE5hbWUiOiJPYmFyZW1pIiwiZW1haWwiOiJwcml5ZW9iaUBnbWFpbC5jb20iLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTYxMTEyNDU2MiwiZXhwIjoxNjExMTQ2MTYyfQ.ff3Y31SVZsaBfoYkopZL-3ACx5P3vFCsqRlX7HYhvBs

###

# For adding a Post 
POST http://localhost:5000/api/posts
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMDk2YWM0NTBiZGJmMWJhMzA5YzFlZiIsImZpcnN0TmFtZSI6IkN5bnRoaWEiLCJsYXN0TmFtZSI6Ik9rZWtlIiwiZW1haWwiOiJva2VrZUBnbWFpbC5jb20iLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTYxMTI2NDY4MSwiZXhwIjoxNjExMjg2MjgxfQ.IWVpMxcC71JonowksthoVE3xMyzduQqqCH3MCMYRZxU

{
    "name": "About Organization",
    "text": "What is DHIStance? DHIStance is the fastest",
    "category": "5ff5cdb838835962e23ab00e",
    "draft": true,
    "owner": "5ff47dc8f4e29d970f27f54b"   
}

###

# For listening all post
GET http://localhost:5000/api/posts
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMDlmNjAwY2FlZGViOTBkNjRkM2JmZSIsImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJCYXJvbiIsImVtYWlsIjoicHJpeWVvYmlAZ21haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTEyNjYyOTAsImV4cCI6MTYxMTI4Nzg5MH0.4Q7v4Vqli9iSk5G7DyYin0lgNGfVwKVxkUUHZLRVEYk
####

GET http://localhost:5000/api/posts/60095bde8d960ad8ea5d0419
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMDk2YWM0NTBiZGJmMWJhMzA5YzFlZiIsImZpcnN0TmFtZSI6IkN5bnRoaWEiLCJsYXN0TmFtZSI6Ik9rZWtlIiwiZW1haWwiOiJva2VrZUBnbWFpbC5jb20iLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTYxMTIzMDU1OCwiZXhwIjoxNjExMjUyMTU4fQ.J2sfh3hx1E9MD3pcHvGzgbluU3227J1V5a7sgcn3cq4

####

DELETE http://localhost:5000/api/posts/6007d3cf44a8c5618ca575d9
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjQ3ZGM4ZjRlMjlkOTcwZjI3ZjU0YiIsImZpcnN0TmFtZSI6IlByaXllIiwibGFzdE5hbWUiOiJPYmFyZW1pIiwiZW1haWwiOiJwcml5ZW9iaUBnbWFpbC5jb20iLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTYxMTE4MTE4NywiZXhwIjoxNjExMjAyNzg3fQ.ZuK9ofvDrMNbA3VlbRBrvwpyXSHpuZI-gz3vuVMFU8U