# For making a post request to login a user
POST http://localhost:5000/api/users/login
content-type: application/json

{
    "email": "priyeobi@gmail.com",
    "password": "admin12345"
}

###

# For making request to get all the user's on the database
GET http://localhost:5000/api/users/
Content-Type: application/json

###

#For getting user by id
GET http://localhost:5000/api/users/5f9e7d8b315bb90f842893ae
Content-Type: application/json

###

# For registering a user into the database
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "firstName": "Priye",
  "lastName": "Obaremi",
  "email": "priyeobi@gmail.com",
  "password": "admin12345",
  "password2": "admin12345"
}

###

#For deleting a user
DELETE http://localhost:5000/api/users/5faa703494ecb24484934df3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOWU3ZDhiMzE1YmI5MGY4NDI4OTNhZSIsImVtYWlsIjoicGFzdG9yQGdtYWlsLmNvbSIsImlhdCI6MTYwNTAwNjEwMCwiZXhwIjoxNjA1MDI3NzAwfQ.4PKxUP_Yzhb8fdiGPTcsPvuqOaaUyoWae8JWKlqs-4E

###

# For adding a Category 
POST http://localhost:5000/api/posts/category
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjQ3ZGM4ZjRlMjlkOTcwZjI3ZjU0YiIsImVtYWlsIjoicHJpeWVvYmlAZ21haWwuY29tIiwiaWF0IjoxNjA5OTI3MjMyLCJleHAiOjE2MDk5NDg4MzJ9.DtQlZDo2ffLM6uaI154rvJnq90rW2hlhEqAG06Lr5RY

{
    "name": "Ofice matters"
}


###

# For adding a Post 
POST http://localhost:5000/api/posts
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjQ3ZGM4ZjRlMjlkOTcwZjI3ZjU0YiIsImVtYWlsIjoicHJpeWVvYmlAZ21haWwuY29tIiwiaWF0IjoxNjA5OTI3MjMyLCJleHAiOjE2MDk5NDg4MzJ9.DtQlZDo2ffLM6uaI154rvJnq90rW2hlhEqAG06Lr5RY

{
    "name": "Having my Appraisal",
    "text": "In the age of layered architecture and microservices",
    "category": "5ff58aa0f2f7d803f48a5a96",
    "draft": false
    
}

###

# For listening all post
POST http://localhost:5000/api/posts
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjQ3ZGM4ZjRlMjlkOTcwZjI3ZjU0YiIsImVtYWlsIjoicHJpeWVvYmlAZ21haWwuY29tIiwiaWF0IjoxNjA5OTI3MjMyLCJleHAiOjE2MDk5NDg4MzJ9.DtQlZDo2ffLM6uaI154rvJnq90rW2hlhEqAG06Lr5RY
